import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { createPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = createPageMetadata("Privacy Policy, Terms and conditions.", "Privacy Policy, Terms and conditions.", "/privacy");

export default function PrivacyPage() {
  return <div className="page-shell"><header className="page-hero container narrow-page"><h1>Privacy Policy, Terms and conditions.</h1><p>Last Updated: August, 2026</p></header><article className="container legal-page">
    <p>Welcome to the website of {siteConfig.author.name}, {siteConfig.author.credentials} (&quot;we,&quot; &quot;our,&quot; or &quot;this website&quot;). Protecting your privacy is important to us. This Privacy Policy explains how information may be collected, used, stored, and protected when you visit our website.</p>
    <p>By using this website, you agree to the practices described in this Privacy Policy.</p>
    <section><h2>Who We Are</h2><p>This website is an educational platform created by {siteConfig.author.name}, {siteConfig.author.credentials}, an obstetrician and gynecologist, with the purpose of providing evidence-based information on women&apos;s health, gynecology, pregnancy, breast health, fertility, and preventive healthcare.</p></section>
    <section><h2>Information We Collect</h2><h3>Information You Provide Voluntarily</h3><p>You may choose to provide information when you:</p><ul><li>Contact us through a contact form</li><li>Send an email</li><li>Subscribe to a newsletter (if available)</li><li>Submit comments or feedback (if enabled)</li></ul><p>This information may include:</p><ul><li>Name</li><li>Email address</li><li>Any information you choose to include in your message</li></ul><p>Please do not send confidential medical information or personal health records through this website.</p></section>
    <section><h2>Information Collected Automatically</h2><p>Like most websites, certain technical information may be collected automatically, including:</p><ul><li>IP address</li><li>Browser type</li><li>Device type</li><li>Operating system</li><li>Pages visited</li><li>Date and time of visit</li><li>Referring website</li><li>General geographic location (such as country or region)</li></ul><p>This information helps us understand how visitors use the website and improve its performance.</p></section>
    <section><h2>Cookies</h2><p>This website may use cookies and similar technologies to:</p><ul><li>Improve website functionality</li><li>Remember user preferences</li><li>Analyze website traffic</li><li>Measure website performance</li></ul><p>You can control or disable cookies through your browser settings. Disabling cookies may affect certain website features.</p></section>
    <section><h2>Analytics</h2><p>We may use website analytics services, such as Google Analytics or similar tools, to better understand visitor behavior.</p><p>These services may collect anonymous information regarding website usage but do not identify individual users.</p></section>
    <section><h2>How We Use Information</h2><p>Information collected may be used to:</p><ul><li>Respond to inquiries</li><li>Improve website content</li><li>Enhance user experience</li><li>Monitor website performance</li><li>Maintain website security</li><li>Analyze website traffic</li><li>Send newsletters or updates if you have subscribed</li></ul><p>We do not sell personal information to third parties.</p></section>
    <section><h2>Medical Information</h2><p>This website is intended for educational purposes only.</p><p>We do not request or intentionally collect personal medical information.</p><p>Please do not submit:</p><ul><li>Medical records</li><li>Laboratory reports</li><li>Imaging studies</li><li>Personal health information</li><li>Prescription details</li></ul><p>If you require medical advice, please consult your own healthcare professional.</p></section>
    <section><h2>Third-Party Links</h2><p>This website may contain links to external websites, including medical organizations, journals, societies and educational resources.</p><p>We are not responsible for the privacy practices, security, or content of third-party websites. We encourage users to review the privacy policies of any external websites they visit.</p></section>
    <section><h2>Data Security</h2><p>Reasonable administrative and technical measures are used to help protect information submitted through this website.</p><p>However, no method of internet transmission or electronic storage is completely secure. While we strive to protect your information, we cannot guarantee absolute security.</p></section>
    <section><h2>Children&apos;s Privacy</h2><p>This website is intended for a general audience and is not specifically directed toward children under the age of 13. We do not knowingly collect personal information from children.</p></section>
    <section><h2>International Visitors</h2><p>If you access this website from outside your country of residence, your information may be processed in accordance with the laws applicable to the location where the website is operated.</p><p>By using this website, you acknowledge that data protection laws may differ between countries.</p></section>
    <section><h2>Your Rights</h2><p>Depending on your location and applicable privacy laws, you may have the right to:</p><ul><li>Request correction of inaccurate information</li><li>Request deletion of personal information</li><li>Withdraw consent where applicable</li><li>Request information about how your data is used</li></ul><p>If you wish to exercise any applicable rights, please contact us using the information provided below.</p></section>
    <section><h2>Changes to This Privacy Policy</h2><p>This Privacy Policy may be updated periodically to reflect changes in legal requirements, technology, or website practices.</p><p>The &quot;Last Updated&quot; date at the top of this page indicates the most recent revision.</p></section>
    <section><h2>Contact</h2><p>If you have questions regarding this Privacy Policy, you may contact us through the website&apos;s contact page or by email (if provided).</p></section>
    <section id="medical-disclaimer"><h2>Medical Disclaimer</h2><p>This website provides general educational information about women&apos;s health.</p><p>The information published on this website is not intended to replace professional medical advice, diagnosis, or treatment.</p><p>Always seek the advice of a qualified healthcare professional regarding any medical concern or emergency.</p></section>
    <p>{siteConfig.copyright}</p>
  </article></div>;
}
