import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { createPageMetadata } from "@/lib/metadata";

export const metadata: Metadata = createPageMetadata("Privacy Policy & Medical Disclaimer", "Privacy practices, contact form information, user rights, and the medical disclaimer for this educational women's health website.", "/privacy");

export default function PrivacyPage() {
  return <div className="page-shell"><header className="page-hero container narrow-page"><p className="eyebrow">Privacy & medical disclaimer</p><h1>Privacy Policy & Medical Disclaimer</h1><p>Last Updated: August 2026</p></header><article className="container legal-page">
    <p>Welcome to the website of {siteConfig.author.name}, {siteConfig.author.credentials} (“we,” “our,” or “this website”). Protecting your privacy is important to us. This Privacy Policy explains how information may be collected, used, stored, and protected when you visit the website. By using this website, you agree to the practices described in this Privacy Policy.</p>
    <section><h2>Who we are</h2><p>This website is an educational platform created by {siteConfig.author.name}, {siteConfig.author.credentials}, {siteConfig.author.role}, with the purpose of providing evidence-based information on women’s health, gynecology, pregnancy, breast health, fertility, and preventive healthcare.</p></section>
    <section><h2>Information we collect</h2><h3>Information you provide voluntarily</h3><p>You may choose to provide information when you contact us through the contact form or send an email if an address is provided. A newsletter or comments may be offered only if those features are enabled in the future; neither is currently available.</p><p>Information you provide may include your name, email address, and anything you choose to include in your message. The website does not provide accounts, appointments, patient portals, or file uploads.</p></section>
    <section><h2>Medical information policy</h2><p>Do not send medical records, laboratory reports, imaging studies, personal health information, prescription details, or other sensitive health information. Contact messages are for general, non-urgent website communication only.</p></section>
    <section><h2>Information collected automatically</h2><p>The hosting and email-delivery providers may process ordinary technical information needed to serve the website, secure requests, diagnose failures, and deliver configured messages. Depending on provider settings, this may include an IP address, browser type, device type, operating system, pages visited, date and time of visit, referring website, general geographic location such as country or region, and delivery events. The application does not create a user profile or store contact submissions in its own database.</p></section>
    <section><h2>Cookies</h2><p>The policy permits cookies and similar technologies to be used to improve functionality, remember preferences, analyse traffic, or measure performance. The current application does not intentionally set analytics or marketing cookies. If cookies are added later, users may be able to control them through browser settings, and this policy and any required consent mechanism must be reviewed first.</p></section>
    <section><h2>Analytics</h2><p>Analytics services such as Google Analytics or similar tools may be considered to understand website use, but no analytics service or tracking script is currently installed. Analytics must not be enabled until its privacy impact and policy requirements have been reviewed.</p></section>
    <section><h2>How we use information</h2><p>Information may be used to respond to inquiries, improve website content and user experience, monitor performance, maintain security, analyse traffic if analytics is later enabled, and send updates only if a user has subscribed to a future newsletter. We do not sell personal information to third parties.</p></section>
    <section><h2>Third-party services and links</h2><p>When configured, contact delivery uses Resend. Hosting is intended for Vercel. Article references may lead to third-party websites with their own privacy practices. A link does not imply control of, or responsibility for, another website’s content or privacy practices.</p></section>
    <section><h2>Data security</h2><p>Reasonable technical safeguards include server-side validation, no file uploads, server-only credentials, restrictive browser headers, and abuse controls. No internet transmission can be guaranteed completely secure. Provider access, retention, and account security must be configured by the site owner.</p></section>
    <section><h2>Children’s privacy</h2><p>This website is intended for a general audience and is not specifically directed toward children under the age of 13. We do not knowingly collect personal information from children.</p></section>
    <section><h2>International visitors</h2><p>If you access this website from outside your country of residence, information may be processed in accordance with the laws applicable to the location where the website is operated. By using this website, you acknowledge that data protection laws may differ between countries.</p></section>
    <section><h2>Your rights</h2><p>Depending on your location and applicable privacy laws, you may have the right to request correction of inaccurate information, request deletion of personal information, withdraw consent where applicable, or request information about how your data is used. Use the website’s contact page to make an applicable request until a confirmed privacy email is provided.</p></section>
    <section><h2>Changes to this policy</h2><p>This page may be updated when the website, providers, or legal requirements change. The “Last Updated” label should change only when a real policy review occurs.</p></section>
    <section><h2>Contact</h2><p>If you have questions about this Privacy Policy, contact us through the website’s contact page or by email if an address is provided in the future.</p></section>
    <section id="medical-disclaimer"><h2>Medical disclaimer</h2><p>{siteConfig.medicalDisclaimer} Content cannot account for an individual’s history, examination, tests, or circumstances. Consult an appropriate healthcare professional regarding medical questions. If you believe you are experiencing a medical emergency, contact an appropriate emergency healthcare service immediately. This website is not an emergency or telemedicine service.</p></section>
    <section><h2>Copyright</h2><p>{siteConfig.copyright}</p></section>
  </article></div>;
}
